### ISSUE TITLE
Add new props

### ISSUE THREAD

**Issue by wangqianwen0418** [gosling-lang/gosling-react#1]
Thanks a lot for wrapping Gosling as a react component!
Good job 👍 

Here are some minor components:
1. maybe specify in the README that the `padding` prop is supported
2. Can we support some commonly used props such as 'className', `style`. I feel they are very useful

**Comment by sehilyi** [comment]
Thank you for reporting!

This issue has been fixed by b1f5d60 and https://github.com/gosling-lang/gosling.js/pull/419
